### ISSUE TITLE
PostgresSQL extension not initializing

### ISSUE THREAD

**Issue by motasima19** [microsoft/vscode-postgresql#104]
- PGSQL Extension Version: 14
- VSCode Version: 1.59.0
- OS Version: darwin arm 64

Steps to Reproduce:

1. sqlserviceinitialization taking longer time.
2.  install postgressql (microsoft), tried to run query. 
<img width="1440" alt="Screen Shot 2021-10-13 at 7 20 33 PM" src="https://user-images.githubusercontent.com/45038030/137225788-7e85bd20-2287-4731-9fd3-044bbee85013.png">

Half an hr, yet not initialized

**Comment by vvilhonen** [comment]
I see this in my extension host log
```
[2021-12-06 20:21:28.793] [exthost] [error] Activating extension ms-ossdata.vscode-postgresql failed due to an error:
[2021-12-06 20:21:28.793] [exthost] [error] TypeError: Cannot read property 'toString' of undefined
	at ServiceDownloadProvider.getDownloadFileName (/Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceDownloadProvider.js:31:47)
	at /Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceDownloadProvider.js:86:35
	at new Promise (<anonymous>)
	at ServiceDownloadProvider.installSQLToolsService (/Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceDownloadProvider.js:85:16)
	at /Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/server.js:78:43
	at new Promise (<anonymous>)
	at ServerProvider.downloadServerFiles (/Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/server.js:76:16)
	at SqlToolsServiceClient.<anonymous> (/Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceclient.js:164:70)
	at Generator.next (<anonymous>)
	at /Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceclient.js:11:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceclient.js:7:12)
	at /Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceclient.js:157:89
	at tryCatcher (/Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/util.js:26:23)
	at Promise._settlePromiseFromHandler (/Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/promise.js:510:31)
	at Promise._settlePromiseAt (/Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/promise.js:584:18)
	at Promise._settlePromises (/Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/promise.js:700:14)
	at Async._drainQueue (/Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/async.js:123:16)
	at Async._drainQueues (/Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/async.js:133:10)
	at Immediate.Async.drainQueues (/Users/user/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/async.js:15:14)
	at processImmediate (internal/timers.js:461:21)
```

**Comment by pouyakary** [comment]
I see the exact problem as well and it's because the extension has no arm64 support on mac

**Comment by DanielRamosAcosta** [comment]
any workaround?

**Comment by dzsquared** [comment]
The changes made to the mssql-vscode extension are nearly identical to the changes needed for this extension: https://github.com/microsoft/vscode-mssql/pull/16969/files

**Comment by pouyakary** [comment]
@dzsquared thanks for this PR! hope to have the extension in M1 soon

**Comment by ryboe** [comment]
There's a native Apple Silicon version of SqlToolsService as of [the 1.42.0 (March 2023) release](https://github.com/microsoft/azuredatastudio/releases/tag/1.42.0) of Azure Data Studio.
