### ISSUE TITLE
Fails to install on VSCode 1.63 /Kubunutu 20.10

### ISSUE THREAD

**Issue by reporter123** [microsoft/vscode-postgresql#109]
- PGSQL Extension Version:0.3.0
- VSCode Version: 1.63.2
OS Version: Linux x64 5.11.0-41-generic
Kubutu 21.10
Python 3.9 globally installed

Steps to Reproduce:

1. Install extension

python crashes while installing pgsqltoolsservice.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "pgsqltoolsservice/pgtoolsservice_main.py", line 11, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/__init__.py", line 17, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/attach_server.py", line 35, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/visualstudio_py_debugger.py", line 24, in <module>
  File "/usr/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 3:38:58 PM] Connection to server got closed. Server will not be restarted.

Python 3.6 is not natively installed on my system I have no idea where those paths are coming from.

**Comment by MuminKhan** [comment]
You can install that dependency manually as a workaround: 

```
curl -LO http://archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
sudo apt install ./libffi6_3.2.1-8_amd64.deb
```

**Comment by urmzd** [comment]
Experienced the same issue. The solution provided by @MuminKhan works. However, if for some reason it doesn't work for you, there's these [alternatives](https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6/63329830#63329830)
