### ISSUE TITLE
Problems after installation. Extension initializing

### ISSUE THREAD

**Issue by ecastellongl** [microsoft/vscode-postgresql#132]
- PGSQL Extension Version:  v0.3.0
- Visual Studio Code : 
Version: 1.92.2 (Universal)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

- OS Version: macOS Sonoma 14.6.1

Steps to Reproduce:

1. Open Visual Studio
2. Install Extension
3. Try to create a new query
4. 
<img width="487" alt="image" src="https://github.com/user-attachments/assets/317261f1-6023-463a-bc19-1ae5ae8b8aeb">

5. PostgreSQL: Unable to execute the command while the extension is initializing. Please try again later.

**Comment by orsisam** [comment]
I have same issue too,

Visual Studio Code Version: 1.94.0
OS Version: Ubuntu 24.04

**Comment by orsisam** [comment]
> I have same issue too,
> 
> Visual Studio Code Version: 1.94.0 OS Version: Ubuntu 24.04

I've fixed this issue. The error is caused by the pgsqltoolsservices. I removed the old one and copied the newest code of pgsqltoolsservices. You can get the pgtoolsservices [here](https://github.com/microsoft/pgtoolsservice/releases/download/v1.10.0/pgsqltoolsservice-linux-x64.tar.gz)

**Comment by orsisam** [comment]
> I have same issue too,
> 
> Visual Studio Code Version: 1.94.0 OS Version: Ubuntu 24.04

This was fixed by installing the newest pgtoolsservices. just replace the old one with the latest version. Here I use version 1.10.

Link: [https://github.com/microsoft/pgtoolsservice/releases?page=1](https://github.com/microsoft/pgtoolsservice/releases?page=1)

**Comment by orsisam** [comment]
> [@orsisam](https://github.com/orsisam) Didn't work for me. Can you please specify EXACTLY where to place it?
> 
>     * I tried: placing it in a number of different places inside of ms-ossdata.vscode-postgresql-0.3.0/pgsqltoolsservice but nothing worked.
> 
>     * I even tried: renaming it to `pgtoolsservice_main` because that was the filename that [here](https://github.com/search?q=repo%3Amicrosoft%2Fvscode-postgresql+pgsqltoolsservice&type=code) but that didn't work either.
> 
> 
> Yes, I would restart the extension after each try.

I placed it on `.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/pgsqltoolsservice/v1.4.0/Ubuntu16`  and renamed the executable file to `pgtoolservice_main`.

**Comment by snobb** [comment]
I made it work by performing the following steps:
1. I've changed the `~/.vscode-oss/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/config.json` to be like this (I'm on arm64 mac):
```{
    "service": {
        "downloadUrl": "https://github.com/microsoft/pgtoolsservice/releases/download/{#version#}/pgsqltoolsservice-{#fileName#}",
        "version": "v1.10.0",
        "downloadFileNames": {
            "Windows_7_86": "win-x86.zip",
            "Windows_7_64": "win-x64.zip",
            "OSX_10_11_64": "osx.tar.gz",
            "CentOS_7": "linux-x64.tar.gz",
            "Debian_8": "linux-x64.tar.gz",
            "Fedora_23": "linux-x64.tar.gz",
            "OpenSUSE_13_2": "linux-x64.tar.gz",
            "SLES_12_2": "linux-x64.tar.gz",
            "RHEL_7": "linux-x64.tar.gz",
            "Ubuntu_14": "linux-x64.tar.gz",
            "Ubuntu_16": "linux-x64.tar.gz",
            "Unknown": "osx-arm64.tar.gz"
        },
        "installDir": "../pgsqltoolsservice/{#version#}/{#platform#}",
        "executableFiles": [
            "pgsqltoolsservice/ossdbtoolsservice_main",
            "pgsqltoolsservice/ossdbtoolsservice_main.exe"
        ]
    }
}
```
2. I downloaded the tarball manually and unzipped it into `~/.vscode-oss/extensions/ms-ossdata.vscode-postgresql-0.3.0/pgsqltoolsservice/v1.10.0/Unknown/`.
3. I ran the ossdbtoolsservice_main manually and then allowed opening in Settings->Security & Privacy.
4. Restarted VSCodium
5. It worked 🎉

**Comment by cssinate** [comment]
This worked for me as well, but even after following all of the above, running the queries from the Command Palette works, but I don't have the icon in the left Actions bar. Is that the case for anyone else?

**Comment by dr-impossible** [comment]
Looking in the output tab for Extension Host, I happened to see this stack trace in the logs. I'm running MacOS on Apple Silicon and I don't think the current version of the extension is generating the correct platform ID for my OS. My config.json also didn't have an entry for service.downloadFileNames.Unknown, but adding this didn't help
```
2025-02-26 14:13:02.560 [error] Activating extension ms-ossdata.vscode-postgresql failed due to an error:
2025-02-26 14:13:02.560 [error] TypeError: Cannot read properties of undefined (reading 'toString')
    at ServiceDownloadProvider.getDownloadFileName (/Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceDownloadProvider.js:31:47)
    at /Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceDownloadProvider.js:86:35
    at new Promise (<anonymous>)
    at ServiceDownloadProvider.installSQLToolsService (/Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceDownloadProvider.js:85:16)
    at /Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/server.js:78:43
    at new Promise (<anonymous>)
    at ServerProvider.downloadServerFiles (/Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/server.js:76:16)
    at SqlToolsServiceClient.<anonymous> (/Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceclient.js:164:70)
    at Generator.next (<anonymous>)
    at /Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceclient.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceclient.js:7:12)
    at /Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/out/src/languageservice/serviceclient.js:157:89
    at tryCatcher (/Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/adam/.vscode/extensions/ms-ossdata.vscode-postgresql-0.3.0/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate (node:internal/timers:483:21)
```
