### ISSUE TITLE
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by FilipLaurentiu** [microsoft/vscode-postgresql#82]
- PGSQL Extension Version: v0.3.0
- VSCode Version: 1.47.0
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. install the extension
2. Try to make a connection

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "pgsqltoolsservice/pgtoolsservice_main.py", line 11, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/__init__.py", line 17, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/attach_server.py", line 35, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/visualstudio_py_debugger.py", line 24, in <module>
  File "/usr/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 10:05:43] Connection to server got closed. Server will not be restarted.
```

**Comment by flowHater** [comment]
Duplicated from https://github.com/microsoft/vscode-postgresql/issues/77
