### ISSUE TITLE
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bsharma06** [microsoft/vscode-postgresql#94]
- PGSQL Extension Version: 2.8.6
- VSCode Version: 1.55.2
- OS Version: Ubuntu 21.04 GNOME Version 3.38.5

**Steps to Reproduce:**

1. Ctrl+Shift+P
2. PostgreSQL: New Query

**Error:**

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "pgsqltoolsservice/pgtoolsservice_main.py", line 11, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/__init__.py", line 17, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/attach_server.py", line 35, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/visualstudio_py_debugger.py", line 24, in <module>
  File "/usr/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 10:35:10 pm] Connection to server got closed. Server will not be restarted.

**Comment by warcayac** [comment]
Same error on Manjaro KDE Plasma.

**Comment by drazisil** [comment]
@warcayac In our case, at least, it is likely because Manjaro is Arch, not Ubuntu or Debian. There doesn't seem to be a version for that: https://github.com/Microsoft/vscode-postgresql/releases
